@startuml
class FirmwareSigner
{
    + {static} sign(rsaKey: string, firmware: Uint8Array): Uint8Array
}

class HexConvert
{
    + {static} binaryToHexString(binary: Uint8Array): string
    + {static} hexStringToBinary(hexString: string): Uint8Array
}

enum LogLevel
{
    LEVEL_INVALID = 4
    LEVEL_DEBUG = 3
    LEVEL_INFO = 2
    LEVEL_WARN = 1
    LEVEL_ERROR = 0
}

class Log
{
    - {static} m_logLevel = LogLevel_DEBUG
    - {static} writeLog(level: LogLevel, msg: string): void
    + {static} setLogLevel(level: LogLevel): void
    + {static} getLogLevel(): LogLevel
    + {static} debug(msg: string): void
    + {static} info(msg: string): void
    + {static} warn(msg: string): void
    + {static} error(msg: string): void
}
Log ..> LogLevel : uses
@enduml
