@startuml
class ConnectivityCOM
{
    - credentials: NetworkCredentials
    - useSTAMode: boolean
    - type: string
    - confirmDialogVisible: boolean
    - infoText: string
    - save(): void
    - declineClick(): void
    - acceptClick(): void
}
ConnectivityCOM "*" *--> "1" NetworkCredentials

class Flash
{
    - type: string
    - flashEnabled: boolean
    - confirmDialogVisible: boolean
    - infoText: string
    - flash: Promise<void> {async}
}

class Home
{
}

class Settings
{
    - selectedMenuEntry: string
    - hideView: boolean
    - entryClick(event: any, item: string): void
}

class Upload
{
    - options: Object[]
    - uploadOption: Object
    - uploadProgressPercent: number
    - uploadActive: boolean
    - update: boolean
    - type: string
    - infoDialogVisible: boolean
    - infoText: string
    - fnPtr: any
    - uploadPackets(firmwareBinary: Uint8Array): Promise<boolean> {async}
    - upload(firmwareBinary: Uint8Array): void
    - save(firmwareBinary: Uint8Array, firmwareHeader: FirmwareHeader): void
    - uploadFirmware(data: any): Promise<void> {async}
    - flashFirmware(): void
}

class App
{
    - type: string
    - infoDialogVisible: boolean
    - infoText: string
    - registerWSEvents(): void
}
@enduml
