@startuml
package Client {
    interface "HTTPS" as https
    interface "WSS" as wss
    interface "RRH" as rrh

    component "VuexStore" as store
    component "VueRouter" as router

    package Models {
        component ApiRequest
        component ApiResponse
        component Firmware
        component FirmwareHeader
        component FirmwareInfo
        component NetworkCredentials
        component ResponseCode
        component UserCredentials

        ApiResponse ..> ResponseCode
        Firmware ..> FirmwareHeader
    }

    package API {
        component RequestResponseHandler
        component WebSocketClient

        RequestResponseHandler -up-rrh

        RequestResponseHandler ..> ApiRequest
        RequestResponseHandler ..> ApiResponse

        RequestResponseHandler -->WebSocketClient

        WebSocketClient --(wss
    }

    package Utility {
        component FirmwareSigner
        component HexConvert
        component Log
    }

    package Components {
        component FirmwareCard
        component "Header" as headerc
        component LoginDialog
        component SettingsMenu
        component Sidebar
        component TextDialog

        FirmwareCard --(rrh
        headerc --(rrh
        Sidebar --(rrh

        FirmwareCard ..> FirmwareInfo
        FirmwareCard ..> Log
        FirmwareCard ..> LoginDialog

        headerc ..> LoginDialog
        headerc ..> Log

        LoginDialog ..> UserCredentials
        LoginDialog --(rrh
        LoginDialog ..> Log

        Sidebar --(rrh
    }

    package Views {
        component ConnectivityCOM
        component Flash
        component Home
        component Settings
        component Upload

        ConnectivityCOM --(rrh
        Flash --(rrh
        Upload --(rrh

        ConnectivityCOM ..> NetworkCredentials

        Flash ..> FirmwareCard
        Flash ..> Log
        Flash ..> FirmwareInfo
        Flash ..> TextDialog

        Settings ..> ConnectivityCOM
        Settings ..> SettingsMenu

        Upload ..> FirmwareCard
        Upload ..> TextDialog
        Upload ..> Log
        Upload ..> Firmware
        Upload ..> FirmwareHeader
        Upload ..> FirmwareSigner
    }

    package ComPlatform {
        component Server
        Server -up- https
        Server -up- wss
    }
}
@enduml
