@startuml
interface "HTTPS" as https
interface "WSS" as wss

note left of https : Used to fetch the\nweb interface application
note right of wss : Used to consume the\nendpoint services

left to right direction

package Client {
    interface "RequestResponseManager" as requestresponsemanager

    component "VuexStore" as store
    component "RequestResponseHandler" as requestresponsehandler
    component "WebSocketClient" as websocketclient

    requestresponsehandler -up- requestresponsemanager

    websocketclient -down-(wss
    websocketclient -down-(requestresponsemanager

    package Assets {
    }

    package Libraries {
        component "FileSaver" as filesaver
        component "jsrsasign" as rsasign

        note right of filesaver : Allows download of large\nblobs to local FS
        note right of rsasign : Signs the passed firmware image with RSA2048/PKCS#1
    }

    package Components {
        package Dialogs {
            component "AuthDialog" as authdialog
            component "ConfirmDialog" as confirmdialog

            note right of authdialog : Dialog which provides\nuser input for credentials
            note right of confirmdialog : Dialog which provides confirmation
        }
    }

    package Models {
        package API {
            package "RequestModels" as requestmodels {
                component "ApiRequest" as request
                component "UserCredentials" as usercredentials
                component "NetworkCredentials" as networkcredentials
                component "CPSFW" as cpsfw

                note right of request : ApiRequest data model
                note right of usercredentials : UserCredentials data model
                note right of networkcredentials : NetworkCredentials data model
                note right of cpsfw : ComPlatform Signed Firmware data model
            }

            package "ResponseModels" as responsemodels {
                component "ApiResponse" as response
                component "LogEntry" as debuglog
                component "FirmwareInfo" as firmwareinfo

                note right of response : ApiResponse data model
                note right of debuglog : LogEntry data model
                note right of firmwareinfo : FirmwareInfo data model
            }
        }
    }

    package Modules {
        package Home {
            package Components_Home {
            }

            package Modules_Home {
            }

            component Store_Home
        }

        package Debug {
            package Components_Debug {
            }

            package Modules_Debug {
            }

            component Store_Debug
        }

        package Upload {
            package Components_Upload {
            }

            package Modules_Upload {
            }

            component Store_Upload
        }

        package Flash {
            package Components_Flash {
            }

            package Modules_Flash {
            }

            component Store_Flash
        }

        package Reboot {
            package Components_Reboot {
            }

            package Modules_Reboot {
            }

            component Store_Reboot
        }
    }

    package Shared {
    }

    package Styles {
    }
}

package ComPlatform {
    component Server
    Server -- https
    Server -- wss
}
@enduml