@startuml
interface "HTTPS" as https
interface "WSS" as wss

package ComPlatform {
    component Server
    Server -up- https
    Server -up- wss
}

package Client {

    interface "RRH" as rrh

    package Models {
        component ApiRequest
        component ApiResponse
        component Firmware
        component FirmwareHeader
        component FirmwareInfo
        component NetworkCredentials
        component ResponseCode
        component UserCredentials

        ApiResponse .down.> ResponseCode
        Firmware .down.> FirmwareHeader
    }

    package API {
        component RequestResponseHandler
        component WebSocketClient

        RequestResponseHandler -up-rrh

        RequestResponseHandler .down.> ApiRequest
        RequestResponseHandler .down.> ApiResponse

        RequestResponseHandler -->WebSocketClient

        WebSocketClient -down-(wss
    }

    package Utility {
        component FirmwareSigner
        component HexConvert
        component Log
    }

    package Components {
        component FirmwareCard
        component "Header" as headerc
        component LoginDialog
        component SettingsMenu
        component Sidebar
        component TextDialog

        FirmwareCard --(rrh
        headerc -down-(rrh
        Sidebar -down-(rrh

        FirmwareCard .down.> FirmwareInfo
        FirmwareCard .down.> Log
        FirmwareCard .down.> LoginDialog

        headerc .down.> LoginDialog
        headerc .down.> Log

        LoginDialog .down.> UserCredentials
        LoginDialog -down-(rrh
        LoginDialog .down.> Log

        Sidebar -down-(rrh
    }

    package Views {
        component ConnectivityCOM
        component Flash
        component Home
        component Settings
        component Upload

        ConnectivityCOM -down-(rrh
        Flash -down-(rrh
        Upload -down-(rrh

        ConnectivityCOM .down.> NetworkCredentials

        Flash .down.> FirmwareCard
        Flash .down.> Log
        Flash .down.> FirmwareInfo
        Flash .down.> TextDialog

        Settings .down.> ConnectivityCOM
        Settings .down.> SettingsMenu

        Upload .down.> FirmwareCard
        Upload .down.> TextDialog
        Upload .down.> Log
        Upload .down.> Firmware
        Upload .down.> FirmwareHeader
        Upload .down.> FirmwareSigner
    }


}
@enduml
