@startuml
' Server interface
interface "WSS"
interface "HTTPS"

component "Client" as client {
    client -down-(WSS
    client -down-(HTTPS
}

package ComPlatform {
    ' API interface
    interface "Command"
    interface "BinaryCommand"

    ' HAL inteface (with Arduino framework + ESP-IDF)
    interface "ComReset"
    interface "ReadKey"
    interface "Crypto"
    interface "mbedTLS"
    interface "WiFi"
    interface "DNS"
    interface "mDNS"
    interface "OTA"
    interface "FS"
    interface "NVS"
    interface "IO"
    interface "Zumo32U4"

    ' System Services interface
    interface "File"
    interface "CryptoServices"
    interface "NVSManager"
    interface "Logging"
    interface "FWCheck"
    interface "System"

    ' Data interface
    interface "Store"

    component "Hardware" as hardware {
        port " " as hardwareport
    }

    component "HAL" {
        HAL-up-ComReset
        HAL-up-IO
        HAL-up-ReadKey
        HAL-up-Zumo32U4
        HAL-up-Crypto
        HAL-up-mbedTLS
        HAL-up-WiFi
        HAL-up-DNS
        HAL-up-mDNS
        HAL-up-OTA
        HAL-up-FS
        HAL-up-NVS

        HAL-down->hardwareport
    }
    note right of HAL : Hardware drivers and\nArduino Framework/ESP-IDF services

    component "Data" {
        Data-up-Store
        Data-down-(NVSManager
    }
    note left of Data : Global data store; Loads and saves\nall settings from/to NVS

    component "SystemServices" {
        SystemServices-up-FWCheck
        SystemServices-up-File
        SystemServices-up-CryptoServices
        SystemServices-up-NVSManager
        SystemServices-up-System
        SystemServices-up-Logging

        SystemServices-down-(ReadKey
        SystemServices-down-(Crypto
        SystemServices-down-(mbedTLS
        SystemServices-down-(FS
        SystemServices-down-(WiFi
        SystemServices-down-(DNS
        SystemServices-down-(mDNS
        SystemServices-down-(NVS
        SystemServices-down-(Store
        SystemServices-down-(ComReset
        SystemServices-down-(IO
    }
    note right of SystemServices : Further HAL abstraction, system init/tools

    component "API"{
        API -up- BinaryCommand
        API -up- Command

        API-down-(File
        API-down-(Store
        API-down-(FWCheck
        API-down-(OTA
        API-down-(Zumo32U4
        API-down-(CryptoServices
        API-down-(System
    }
    note right of API : API service implementations with stable interface

    component "Server"{
        Server-up-WSS
        Server-up-HTTPS

        Server-down-(File
        Server-down-(Store
        Server-down-(BinaryCommand
        Server-down-(Command
    }
    note right of Server : HTTPs/WSS server which serves frontend/webspace\ncalls/redirects API services and checks permission/authentication
    @enduml
