@startuml System Overview

folder "Server" as server
folder "API" as api
folder "Data" as data
folder "Zumo" as zumo
folder "System Services" as systemservices
folder "HAL" as hal

server .down.> api : <<access>>
zumo .down.> systemservices : <<access>>
data .down.> systemservices : <<access>>
api .down.> systemservices : <<access>>
systemservices .down.> hal : <<access>>
api .right.> data
api .left.> zumo

@enduml