@startuml
package Server {
    component "RequestResponseHandler" as RequestResponseHandler
}

package Commands {
    interface "OTA" as ota
    interface "FWCheck" as FWCheck
    interface "File" as File
    interface "Store" as Store
    interface "Zumo32U4" as Zumo32U4
    interface "System" as System

    component Command
    component "EchoDemoCommand" as echodemocommand
    component "UploadZumoCommand" as uploadzumoservice
    component "FlashZumoCommand" as flashzumoservice
    component "SetSTACredentialsCommand" as credconfig
    component "RebootZumoCommand" as resetzumoservice
    component "RebootCOMCommand" as resetcomplatforomservice
    component "DebugZumoCommand" as zumodebug
    component "UploadCOMCommand" as uploadcomfirmware
    component "FlashCOMCommand" as flashcomfirmware

    Command <|-- echodemocommand
    Command <|-- uploadzumoservice
    Command <|-- flashzumoservice
    Command <|-- credconfig
    Command <|-- resetzumoservice
    Command <|-- resetcomplatforomservice
    Command <|-- zumodebug
    Command <|-- uploadcomfirmware
    Command <|-- flashcomfirmware
    RequestResponseHandler *--> Command

    uploadzumoservice -down-(File
    uploadzumoservice -down-(Store
    uploadzumoservice -down-(FWCheck
    uploadcomfirmware -down-(ota
    uploadcomfirmware -down-(Store
    uploadcomfirmware -down-(FWCheck
    flashcomfirmware -down-(ota
    flashcomfirmware -down-(Store
    flashcomfirmware -down-(System
    credconfig -down-(Store
    flashzumoservice -down-(FWCheck
    flashzumoservice -down-(File
    flashzumoservice -down-(Store
    flashzumoservice -down-(Zumo32U4
    resetzumoservice -down-(Zumo32U4
    resetcomplatforomservice -down-(System
    zumodebug -down-(Zumo32U4
}
@enduml
