@startuml
interface "WSS" as WSS
interface "HTTPS" as HTTPS

interface "File" as File
interface "Store" as Store

package Server {
    component "WebServer" as webserver

    note left of webserver : Serves the HTML/JS/CSS\nfiles for web interface\nand provides access to\nall endpoint services

    webserver -up- WSS
    webserver -up- HTTPS

    webserver -down-(File
    webserver -down-(Store

    component "SessionManager" as sessionsmgmt
    component "RequestResponseHandler" as requesthandler

    note left of sessionsmgmt : Checks and manages active sessions.\nChecks user credentials and permissions
    note left of requesthandler : Parses the incoming JSON request,\nchecks the session rights and invokes\ncorresponding API services

    interface "RequestResponseManager" as Request
    requesthandler -up- Request

    requesthandler *--> sessionsmgmt : checks/requests\naccess/session

    webserver -down-(Request
    sessionsmgmt -down-(Store
}
@enduml
