@startuml
package SystemServices {
    interface "Crypt" as crypthal
    interface "mbedTLS" as mbedtlshal
    interface "NVS" as nvshal
    interface "FS" as fshal
    interface "ReadKey" as readkey
    interface "WiFi" as wifihal
    interface "Store" as store
    interface "System" as systemhal

    interface "File" as File
    interface "Crypt" as Crypt
    interface "NVS" as nvs
    interface "Logging" as Logging

    component "System" as initcom
    component "FirmwareChecker" as firmwarecheck
    component "FirmwareDeserializer" as fwdeserializer
    component "CryptoServices" as cryptoservices
    component "FileManager" as filemanager
    component "NVSManager" as nvsmanager
    component "WiFiManager" as wifilayerhal
    component "Log" as logger

    note left of cryptoservices : Provides hardware-accelerated\nSHA256, BLAKE2b, RSA2048 and TRNG
    note left of fwdeserializer : Converts binary firmware\nfile and checks integrity
    note right of firmwarecheck : Checks target system\nand signature of firmware.\nPublic key hardcoded
    note right of filemanager : Provides abstraction\nfor easy use of\n(buffered) file operations
    note right of nvsmanager : Provides abstraction to store\nkey-value pairs in\nnon-volatile storage
    note left of initcom : Provides init and reset of ComPlatform
    note left of wifilayerhal: Manages AP and STA mode
    note left of logger: Provides easy to use system logging

    filemanager -up- File
    cryptoservices -up- Crypt
    nvsmanager -up- nvs
    initcom -up- systemhal
    logger -up- Logging

    initcom ..> wifilayerhal
    firmwarecheck *--> fwdeserializer

    fwdeserializer -down(crypthal
    nvsmanager -down-(nvshal
    filemanager -down-(fshal
    initcom -down-(readkey
    initcom -down-(store
    wifilayerhal -down-(wifihal
    wifilayerhal -down-(store
    cryptoservices -down-(crypthal
    cryptoservices -down-(mbedtlshal
}
@enduml
