@startuml
package HAL
{
    package "Arduino Core"
    {
        class "Digital I/O" as ArduinoIO
        class SemaphoreHandle_t 
    }

    enum GPIOPins
    {
        WIFI_AND_RESET_KEY_PIN = 0,
        ROBOT_RESET_PIN = 2,
        ANALOG_NOISE_SEED_PIN = 36
    }

    class IO
    {
        - m_ioMutex: SemaphoreHandle_t
        {static} - DEBOUNCE_DELAY_TIME_MS: uint8_t {readonly} = 50
        + {static} getInstance(): IO&
        + setPinMode(gpio: const uint8_t, mode: const uint8_t): void
        + readGPIODebounced(gpio: const uint8_t): uint8_t
        + readGPIO(gpio: const uint8_t): uint8_t
        + writeGPIO(gpio: const uint8_t, value: const uint8_t): void
        - IO()
        - ~IO()
    }
    IO  ..> ArduinoIO : uses
    IO  ..> SemaphoreHandle_t : uses

    class Key
    {
        - m_io : IO&
        {static} - LONG_PRESS_TIME_MS: uint32_t {readonly}  = 1000
        {static} + getInstance(): Key&
        + registerSystemReset(): void
        + readKey(): bool {const}
        - Key()
        - ~Key()
        - {static} resetTask(parameter: void*): void
        - {static} systemResetISR(): void
    }
    Key "0..*" *--> "1" IO
    Key ..> GPIOPins : includes

    class Robot
    {
        - m_io : IO&
        {static} - ROBOT_RESET_TIME_MS: uint32_t {readonly} = 500
        {static} + getInstance(): Robot&
        + resetRobotNow(): void
        - Robot()
        - ~Robot()
    }
    Robot "0..*" *--> "1" IO
    Robot ..> GPIOPins : includes
}
@enduml
