@startuml
package SystemService
{
    class NVSManager
    {
    }
}

package httpsserver
{
    class SSLCert
    {

    }
}

package Data
{
    class NetworkCredentials
    {
        - m_ssid: String
        - m_psk: String

        + NetworkCredentials(ssid: String, psk: String)
        + NetworkCredentials()
        + ~NetworkCredentials()
        + getSSID(): String
        + setSSID(ssid: String): void
        + getPSK(): String
        + setPSK(psk: String): void
        + serialize(): String
        + deserialize(serial: String): bool
    }

    class KeyCert
    {

        + {static} RSA_KEY_SIZE_BYTE : size_t {readonly} = 1190
        + {static} CERT_SIZE_BYTE: size_t {readonly} = 766
        - m_sslCert: httpsserver::SSLCert
        - {static} m_binaryKey: uint8_t[]
        - {static} m_binaryCert: uint8_t[]
        - m_certGenerated: bool = false
        + KeyCert()
        + ~KeyCert()
        + generateNewCert(): bool
        + serialize(keyBuffer: uint8_t*, certBuffer: uint8_t*): void
        + deserialize(keyBuffer: uint8_t*, certBuffer: uint8_t*): void
        - freeSSLMemory(): void
    }
    KeyCert "0..*" *--> "1" SSLCert

    class Store
    {
        - m_nvsmgr: NVSManager
        - m_netCredentials: NetworkCredentials
        - m_keyCert: KeyCert

        - Store()
        - ~Store()
        {static} + getInstance(): Store&
        + saveNetworkCredentials(): bool
        + loadNetworkCredentials(): bool
        + getNetworkCredentials(): NetworkCredentials
        + setNetworkCredentials(credentials: NetworkCredentials): void
        + saveKeyCert(): bool
        + loadKeyCert(): bool
        + getKeyCert(): SSLCert&
        + setKeyCert(keycert: KeyCert): void
    }
    Store "0..*" *--> "1" NVSManager
    Store "0..*" *--> "1" NetworkCredentials
    Store "0..*" *--> "1" KeyCert
}
@enduml