@startuml


package SystemServices
{
    class FirmwareChecker
}

abstract class Command
{
    - m_serviceID: String
    - m_reqPermission: Permission
    + Command(serviceId: const String&, reqPermission: const Permission&)
    + {virtual} ~Command()
    + getServiceID(): const String& {const}
    + getReqPermission(): const Permission& {const}
    + {abstract} run(request: const ApiRequest&, response: ApiResponse&, connectionCtx: Session*): void {const}
    - Command()
    - Command(const Command&)
    - Command& operator =(const Command&);
}

abstract class BinaryCommand
{
    - m_binaryServiceID: String
    - m_BinaryReqPermission: Permission
    + BinaryCommand(serviceId: const String&, reqPermission: const Permission&)
    + {virtual} ~BinaryCommand()
    + getBinaryReqPermission(): const Permission& {const}
    + {abstract} run(response: ApiResponse&, connectionCtx: Session*): void
    + {abstract} reset(): void
    - BinaryCommand()
    - BinaryCommand(const BinaryCommand&)
    - BinaryCommand& operator =(const BinaryCommand&);
}

class EchoDemoCommand
{
    + AuthCommand()
    + ~AuthCommand()
}
Command <|-down-EchoDemoCommand

class FlashZumoCommand
{
    + FlashZumoCommand()
    + ~FlashZumoCommand()
}
Command <|-down-FlashZumoCommand

class UploadZumoCommand
{
    + UploadZumoCommand()
    + ~UploadZumoCommand()
    - m_fileManager: FileManager
    - m_fwChecker: FirmwareChecker
    - {static} FIRMWARE_FILENAME: char* = {readonly} "/zumo_firmware.bin"
    - {static} TARGET_SYSTEM: char* = {readonly} "ZUMO"
    - {static} OVERWRITE_FIRMWAREINFO: bool = {readonly} true
    - m_writtenFirmwareBytes: uint32_t
    - writeFile(dataChunk: const uint8_t*, chunkSize: const uint16_t): bool
}
Command <|-down-UploadZumoCommand
BinaryCommand <|-down-UploadZumoCommand
UploadZumoCommand "0..*" *--> "1" FileManager
UploadZumoCommand "0..*" *--> "1" FirmwareChecker

class UploadZumoCommand
{
    + UploadZumoCommand()
    + ~UploadZumoCommand()
}
Command <|-down-FlashZumoCommand

class RebootZumoCommand
{
    + RebootZumoCommand()
    + ~RebootZumoCommand()

}
Command <|-down-RebootZumoCommand

class ConfigureNetworkCommand
{
    + ConfigureNetworkCommand()
    + ~ConfigureNetworkCommand()
}
Command <|-down-ConfigureNetworkCommand

class RebootCOMCommand
{
    + RebootCOMCommand()
    + ~RebootCOMCommand()
}
Command <|-down-RebootCOMCommand

class DebugZumoCommand
{
    + DebugZumoCommand()
    + ~DebugZumoCommand()
}
Command <|-down-DebugZumoCommand

class FlashCOMCommand
{
    + FlashCOMCommand()
    + ~FlashCOMCommand()
}
Command <|-down-FlashCOMCommand

class UploadCOMCommand
{
    + UploadCOMCommand()
    + ~UploadCOMCommand()
}
Command <|-down-UploadCOMCommand

@enduml
