package SystemServices
{
    class FileManager
}

package Data
{
    class Store
}

class HTTPSServer

class HTTPsWebServer
{
    - {static} SHARED_TCP_PORT: uint16_t = {readonly} 443
    - {static} MAX_CLIENTS: uint8_t = {readonly} = 4
    - {static} m_servedFileTypes: String[][] {readonly}
    - m_httpsServer: httpsserver::HTTPSServer
    - m_fileServeRoute: httpsserver::ResourceNode
    - m_store: Store&
    - {static} m_fileManager: FileManager
    - {static} registerFileServing(request: httpsserver::HTTPRequest*, response: httpsserver::HTTPResponse*): void
    - {static} getMIMEType(filePath: String): String
    + HTTPsWebServer()
    + ~HTTPsWebServer()
    + startServer(): bool
    + stopServer(): bool
    + handleServer(): void
}
HTTPsWebServer ..> FileManager : uses
HTTPsWebServer "0..*" *--> "1" Store
HTTPsWebServer "0..*" *--> "1" HTTPSServer
HTTPsWebServer ..> ResponseCode
