package SystemServices
{
    class FileManager
}

package Data 
{
    class Store
}

class HTTPSServer

class WebServer
{
    - {static} SHARED_TCP_PORT: uint16_t = {readonly} 443
    - {static} MAX_CLIENTS: uint8_t = {readonly} = 4
    - registeredRoutes: ResourceNode[]
    - m_store: Store&
    - m_fileManager: FileManager&
    - m_httpsServer: HTTPSServer
    - registerHome(): bool
    - registerServices(): bool
    + WebServer()
    + ~WebServer()
    + startServer(): bool 
    + stopServer(): bool
    + handleServer(): void
}
WebServer "0..*" *--> "1" FileManager
WebServer "0..*" *--> "1" Store
WebServer "0..*" *--> "1" HTTPSServer