@startuml
partition "System Initialization" {
    (*) --> "Turn on ComPlatform"
    --> "Register Reset-ISR"
    --> === S1 ===
    --> "Start KeyCert generation task"
    --> "Load/set KeyCert from disk"

    if "KeyCert available" then
    --> [true] === S2 ===
    else
    --> [false] "Generate/set new KeyCert"
    --> "Save new KeyCert to disk"
    --> === S2 ===
    endif

    === S1 === --> "Generate unique SSID for AP mode"
    --> "Read WiFi/Reset key"

    if "WiFi/Reset key pressed for two seconds" then
    --> [true] "Init AP" as initap
    else
    --> [false] "Load NetworkCredentials from disk"
    if "Credetentials available" then
    --> [true] "Init STA"
    --> "Initialize file system"
    else
    --> [false] initap
    endif

    --> "Initialize file system"
    --> "Load Users and their Permissions from disk"

    if "User 'admin' existing" then
    --> [true] === S2 ===
    else
    --> [false] "Create user 'admin' with default password and full priviliges"
    --> "Save new user 'admin' to disk"
    endif
    --> === S2 ===
    --> "Start session timeout service"
    if "KeyCert set and session timeout service successfully started" then
    --> [true] "Init HTTPs Server"
    --> "Init WSS Server"
    --> "Service Handling"
    else
    --> "Service Handling"
    endif
}

partition "Service Handling" {
    --> "Handle DNS-Service" as handledns
    --> "Handle Websocket & HTTPs Servers"
    --> "Handle USB Services"
    --> handledns
}
@enduml
