@startuml
(*) --> "Turn on ComPlatform"
--> "Register Reset-ISR"
--> === S1 ===
--> "Start KeyCert generation task"
--> "Load/set KeyCert from disk"

if "KeyCert available" then
    --> [true] "Start/Register session-timeout Timer"
else 
    --> [false] "Generate/set new KeyCert"
    --> "Save new KeyCert to disk"
    --> "Start/Register session-timeout Timer"
endif

=== S1 === --> "Generate unique SSID for AP mode"
--> "Read WiFi/Reset key"

if "WiFi/Reset key pressed for two seconds" then
    --> [true] "Init AP" as initap
else
    --> [false] "Load NetworkCredentials from disk"
    if "Credetentials available" then
        --> [true] "Init STA"
        --> "Initialize file system"
else 
        --> [false] initap
endif

--> "Initialize file system"
--> "Load Users and their Permissions from disk"

if "User 'admin' existing" then
    --> "Start/Register session-timeout Timer"
else
    --> [false] "Create user 'admin' with default password and full priviliges"
    --> "Save new user 'admin' to disk"
endif

--> "Start/Register session-timeout Timer"
--> === S2 ===
--> "Init HTTPs Server"
--> "Init WSS Server"
--> (*)
@enduml
