@startuml
(*) --> "Turn on ComPlatform"
--> "Register Reset-ISR"
--> "Generate unique SSID for AP mode"
--> "Load Users"
--> "Load Permissions"
--> "Read WiFi/Reset key"

if "WiFi/Reset key pressed for two seconds" then
--> [true] "Set UseAP = true"
--> "Load KeyCert" as loadkeycert
else
--> [false] "Set UseAP = false"
--> loadkeycert
endif

if "KeyCert available" then
    --> [true] "Check UseAP"
else 
    --> [false] "Generate new KeyCert"
    --> "Save new KeyCert"
    --> "Check UseAP"
endif

if "UseAP is" then
    --> [true] "Init AP" as initap
else 
    --> [false] "Load NetworkCredentials"
    if "Credetentials available" then
        --> [true] "Init STA"
        --> "Init HTTPs Server"
    else 
        --> [false] initap
    endif
endif

--> "Init HTTPs Server"
--> "Init WSS Server"
--> (*)
@enduml