@startuml
(*) --> "Turn on ComPlatform"
--> "Register Reset-ISR"
--> === S1 ===
--> "Start KeyCert generation task"
--> "Load/set KeyCert from disk"

if "KeyCert available" then
    --> [true] === S2 ===
else 
    --> [false] "Generate/set new KeyCert"
    --> "Save new KeyCert to disk"
    --> === S2 ===
endif

=== S1 === --> "Generate unique SSID for AP mode"
--> "Read WiFi/Reset key"

if "WiFi/Reset key pressed for two seconds" then
    --> [true] "Init AP" as initap
else
    --> [false] "Load NetworkCredentials from disk"
    if "Credetentials available" then
        --> [true] "Init STA"
        --> "Initialize file system"
else 
        --> [false] initap
endif

--> "Initialize file system"
--> "Load Users from disk"
--> "Load Permissions from disk"
--> === S2 ===
--> "Init HTTPs Server"
--> "Init WSS Server"
--> (*)
@enduml
