M48
; DRILL file {KiCad 7.0.1} date Mon Dec 18 13:28:24 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-18T13:28:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.550
%
G90
G05
T1
X126.175Y-142.4
X129.175Y-142.4
T2
X116.53Y-132.71
X177.47Y-60.48
T3
X116.53Y-69.13
X132.27Y-124.33
X161.73Y-68.86
X177.47Y-124.06
T0
M30
